FROM python:3.12-slim

# Set working directory inside container
WORKDIR /backend

# Install uv
RUN pip install uv

# Copy dependency files
COPY ./backend/pyproject.toml /backend/pyproject.toml
# COPY ./backend/uv.lock /backend/uv.lock

# Install dependencies with uv
RUN uv sync

COPY ./backend/app /backend/app

# Run FastAPI with hot reload using uv
CMD ["uv", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8055", "--reload"]
    