version: "3"
services:
  nginx:
    image: nginx
    restart: always
    ports:
      - 80:8000
    volumes:
      - ./nginx-compose.config:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend-compose
    environment:
      BACKEND_BASE_URL: http://localhost/backend
    volumes:
      - /frontend/node_modules
      - ./frontend:/frontend

  database:
    image: postgis/postgis:13-master
    platform: linux/amd64
    volumes:
      - database_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    restart: always
    depends_on:
      - database
    environment:
      - ADMINER_DESIGN=pepa-linha-dark
    ports:
      - 8080:8080

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend-compose
    ports:
      - 8055:8055
    volumes:
      - ./backend/app:/backend/app
    depends_on:
      database:
        condition: service_healthy

volumes:
  database_data:

networks:
  traefik-public:
    # Allow setting it to false for testing
    external: true
